### ISSUE TITLE
Error when using flaschenpost in docker

### ISSUE THREAD

**Issue by nombrekeff** [thenativeweb/flaschenpost#877]
https://github.com/mwiesmueller/node-poeditor/issues/5

I've been using the above package in a nest-js app. node-poeditor uses flaschenpost. But when I try to use it inside a docker image, it throws an error where it does not find the package.json. Any idea how this could be fixed?

The error I receive is: 
```
/node_modules/flaschenpost/dist/readPackageJson.js:16
nest-api    |     throw new Error('Could not find package.json.');
nest-api    |     ^
nest-api    | 
nest-api    | Error: Could not find package.json.
nest-api    |     at readPackageJson (/node_modules/flaschenpost/dist/readPackageJson.js:16:11)
nest-api    |     at Object.flaschenpost.initialize (/node_modules/flaschenpost/dist/flaschenpost.js:23:36)
nest-api    |     at Object.<anonymous> (/node_modules/flaschenpost/dist/flaschenpost.js:111:14)
nest-api    |     at Module._compile (node:internal/modules/cjs/loader:1126:14)
nest-api    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
nest-api    |     at Module.load (node:internal/modules/cjs/loader:1004:32)
nest-api    |     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
nest-api    |     at Module.require (node:internal/modules/cjs/loader:1028:19)
nest-api    |     at require (node:internal/modules/cjs/helpers:102:18)
nest-api    |     at Object.<anonymous> (/node_modules/node-poeditor/lib/workers/request/httprequest.js:4:16)
```

**Comment by goloroden** [comment]
This is hard to tell without looking at the actual code, as it could be caused by how the Docker image is built, how the module is being imported, or lots of other things.

The only thing I can tell is that apparently the `package.json` file is not where it is being looked for.

Sorry 😕

**Comment by nombrekeff** [comment]
No problem! I've just forked the other package and removed flaschenpost, that works for now!
